[workspace]
members = ["crates/tapes-core", "crates/tapes"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Unlicense"

[workspace.dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tapes-core = { path = "crates/tapes-core" }
