[workspace]
members = ["crates/tapes-core", "crates/tapes"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Unlicense"
repository = "https://github.com/11xx/tapes"

[workspace.dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = { version = "0.10", default-features = false }
zip = { version = "2.2", default-features = false, features = ["deflate"] }
tapes-core = { path = "crates/tapes-core", version = "0.1.0" }
